-- The original database had these CHECK constraints before this repo existed,
-- but the baseline migration was generated by `prisma migrate diff`, which
-- doesn't emit CHECK constraints — so a fresh database built from migrations
-- alone would silently lack them. Status values are the ones the code's
-- ALLOWED_TRANSITIONS / payment handling rely on; the numeric checks are
-- defense-in-depth behind zod validation and the atomic stock decrement.
-- Wrapped in existence checks so this is a no-op against the original
-- database, where some of these already exist. See docs/decisions.md.
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'orders_status_check' AND conrelid = 'public.orders'::regclass) THEN
    ALTER TABLE "orders" ADD CONSTRAINT "orders_status_check"
      CHECK ("status" IN ('pending', 'confirmed', 'processing', 'shipped', 'delivered', 'cancelled'));
  END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'payments_status_check' AND conrelid = 'public.payments'::regclass) THEN
    ALTER TABLE "payments" ADD CONSTRAINT "payments_status_check"
      CHECK ("status" IN ('created', 'pending', 'paid', 'failed', 'refunded'));
  END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'product_variants_stock_nonnegative' AND conrelid = 'public.product_variants'::regclass) THEN
    ALTER TABLE "product_variants" ADD CONSTRAINT "product_variants_stock_nonnegative"
      CHECK ("stock_quantity" >= 0);
  END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'product_variants_price_positive' AND conrelid = 'public.product_variants'::regclass) THEN
    ALTER TABLE "product_variants" ADD CONSTRAINT "product_variants_price_positive"
      CHECK ("price_paise" > 0);
  END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'order_items_quantity_positive' AND conrelid = 'public.order_items'::regclass) THEN
    ALTER TABLE "order_items" ADD CONSTRAINT "order_items_quantity_positive"
      CHECK ("quantity" > 0);
  END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'order_items_price_positive' AND conrelid = 'public.order_items'::regclass) THEN
    ALTER TABLE "order_items" ADD CONSTRAINT "order_items_price_positive"
      CHECK ("unit_price_paise" > 0 AND "total_price_paise" > 0);
  END IF;
END $$;
